pipeline{
  agent any
  stages{
    stage('integration')
    {
      steps{
        git 'https://github.com/saikumarvsk/frontendsai.git'
      }
    }
stage('build'){
  steps{
    dir('hrms'){
      script{
        sh 'docker build -t frontend .'
      }
    }
  }
  }
}
}
