pipeline{
  agent any
  stages{
    stage('integration')
    {
      steps{
        git 'https://github.com/saikumarvsk/frontendsai.git'
      }
    }
    stage('Build') {
            steps {
 dir('hrms') {
                script {
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
            }
    }
  }
}
stage('Build Docker Image') {
    steps {
        script {
            dir('hrms') {
                def dockerImageName = 'sai'
                def dockerImage = docker.build(dockerImageName, '-f Dockerfile .')
            }
        }
    }
}
