pipeline{
  agent any
  stages{
    
  stage('integration')
  {
    steps{
      git 'https://github.com/saikumarvsk/frontendsai.git'
    }
    }
stage('build'){
steps{
  dir('hrms'){
    
  
  script{
    sh 'npm install'
    sh 'npm run build'
  }
}

}  
}
stage('Build Docker Image') {
    steps {
        script {
            // Build Docker image for AngularJS app
            dir('hrms') {
                // Set the desired Docker image name
                def dockerImageName = 'sai'

                // Build the Docker image
                def dockerImage = docker.build(dockerImageName, '-f Dockerfile .')

                
            
            }
        }
    }
}


stage("deploy") {
    steps {
        script {
            // Run Docker container for deployment
            docker.image('sai').run('-d -p 8081:4200', '--name sc')
        }
    }
}


    
    
  }
}
